package kanta;
// Generated by ComTest BEGIN
import kanta.*;
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.HetuTarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.06 13:02:11 // Generated by ComTest
 *
 */
public class HetuTarkistusTest {



  // Generated by ComTest BEGIN
  /** testTarkista29 */
  @Test
  public void testTarkista29() {    // HetuTarkistus: 29
    HetuTarkistus hetut = new HetuTarkistus(); 
    assertEquals("From: HetuTarkistus line: 32", "Hetu liian lyhyt", hetut.tarkista("12121")); 
    assertEquals("From: HetuTarkistus line: 33", "Hetu liian lyhyt", hetut.tarkista("k")); 
    assertEquals("From: HetuTarkistus line: 34", "Alkuosassa saa olla vain numeroita", hetut.tarkista("12121k")); 
    assertEquals("From: HetuTarkistus line: 35", null, hetut.tarkista("121212"));  // sallitaan pelkkä syntymäaika
    assertEquals("From: HetuTarkistus line: 36", "Liian pieni päivämäärä", hetut.tarkista("001212")); 
    assertEquals("From: HetuTarkistus line: 37", "Liian suuri päivämäärä", hetut.tarkista("321212")); 
    assertEquals("From: HetuTarkistus line: 38", "Liian suuri päivämäärä", hetut.tarkista("300212")); 
    assertEquals("From: HetuTarkistus line: 39", "Liian suuri päivämäärä", hetut.tarkista("310412")); 
    assertEquals("From: HetuTarkistus line: 40", "Liian suuri kuukausi", hetut.tarkista("121312")); 
    assertEquals("From: HetuTarkistus line: 41", "Liian pieni kuukausi", hetut.tarkista("120012")); 
    assertEquals("From: HetuTarkistus line: 42", "Väärä erotinmerkki", hetut.tarkista("121212B222Q")); 
    assertEquals("From: HetuTarkistus line: 43", "Yksilöosassa kirjaimia", hetut.tarkista("121212-2k2Q")); 
    assertEquals("From: HetuTarkistus line: 44", "Yksilöosa liian lyhyt", hetut.tarkista("121212-2")); 
    assertEquals("From: HetuTarkistus line: 45", "Yksilöosa liian lyhyt", hetut.tarkista("121212-")); 
    assertEquals("From: HetuTarkistus line: 46", "Hetu liian pitkä", hetut.tarkista("121212-12345")); 
    assertEquals("From: HetuTarkistus line: 47", "Tarkistusmerkin kuuluisi olla N", hetut.tarkista("121212-222S")); 
    assertEquals("From: HetuTarkistus line: 48", null, hetut.tarkista("121212-222N")); 
    assertEquals("From: HetuTarkistus line: 49", null, hetut.tarkista("121212-231Y")); 
    assertEquals("From: HetuTarkistus line: 50", null, hetut.tarkista("311212-2317")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHetunTarkistusMerkki86 */
  @Test
  public void testHetunTarkistusMerkki86() {    // HetuTarkistus: 86
    assertEquals("From: HetuTarkistus line: 87", 'N', hetunTarkistusMerkki("121212-222")); 
    assertEquals("From: HetuTarkistus line: 88", 'N', hetunTarkistusMerkki("121212-222S")); 
    assertEquals("From: HetuTarkistus line: 89", 'N', hetunTarkistusMerkki("121212-222N")); 
    assertEquals("From: HetuTarkistus line: 90", 'Y', hetunTarkistusMerkki("121212-231Y")); 
    assertEquals("From: HetuTarkistus line: 91", '7', hetunTarkistusMerkki("311212-2317")); 
    assertEquals("From: HetuTarkistus line: 92", '7', hetunTarkistusMerkki("311212-2317XY"));  // vaikka on liikaa merkkejä
    assertEquals("From: HetuTarkistus line: 93", 'F', hetunTarkistusMerkki("999999-9999XY"));  // vaikka on pvm väärin
    try {
    assertEquals("From: HetuTarkistus line: 94", 'N', hetunTarkistusMerkki("12121A-222S")); 
    fail("HetuTarkistus: 94 Did not throw NumberFormatException");
    } catch(NumberFormatException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: HetuTarkistus line: 95", 'N', hetunTarkistusMerkki("12121A-22")); 
    fail("HetuTarkistus: 95 Did not throw StringIndexOutOfBoundsException");
    } catch(StringIndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: HetuTarkistus line: 96", 'N', hetunTarkistusMerkki("121")); 
    fail("HetuTarkistus: 96 Did not throw StringIndexOutOfBoundsException");
    } catch(StringIndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}