package kanta;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.SisaltaaTarkistaja.*;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.06 13:02:00 // Generated by ComTest
 *
 */
public class SisaltaaTarkistajaTest {



  // Generated by ComTest BEGIN
  /** testOnkoVain25 */
  @Test
  public void testOnkoVain25() {    // SisaltaaTarkistaja: 25
    assertEquals("From: SisaltaaTarkistaja line: 26", false, onkoVain("123","12")); 
    assertEquals("From: SisaltaaTarkistaja line: 27", true, onkoVain("123","1234")); 
    assertEquals("From: SisaltaaTarkistaja line: 28", true, onkoVain("","1234")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkista55 */
  @Test
  public void testTarkista55() {    // SisaltaaTarkistaja: 55
    SisaltaaTarkistaja tar = new SisaltaaTarkistaja("123"); 
    assertEquals("From: SisaltaaTarkistaja line: 57", null, tar.tarkista("12")); 
    assertEquals("From: SisaltaaTarkistaja line: 58", "Saa olla vain merkkejä: 123", tar.tarkista("14")); 
    assertEquals("From: SisaltaaTarkistaja line: 59", null, tar.tarkista("")); 
  } // Generated by ComTest END
}