package kanta;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mainonta.Mielenkiinto;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.06 13:01:45 // Generated by ComTest
 *
 */
public class TietueTest {



  // Generated by ComTest BEGIN
  /** testInt18 */
  @Test
  public void testInt18() {    // Tietue: 18
    Mielenkiinto miel = new Mielenkiinto(); 
    assertEquals("From: Tietue line: 21", 4, miel.getKenttia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt30 */
  @Test
  public void testInt30() {    // Tietue: 30
    Mielenkiinto miel = new Mielenkiinto(); 
    assertEquals("From: Tietue line: 32", 2, miel.ekaKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString42 */
  @Test
  public void testString42() {    // Tietue: 42
    Mielenkiinto miel = new Mielenkiinto(); 
    assertEquals("From: Tietue line: 44", "asia", miel.getKysymys(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString54 */
  @Test
  public void testString54() {    // Tietue: 54
    Mielenkiinto miel = new Mielenkiinto(); 
    miel.parse("   2   |  2  |   Tekniikka  | 3 "); 
    assertEquals("From: Tietue line: 57", "2", miel.anna(0)); 
    assertEquals("From: Tietue line: 58", "2", miel.anna(1)); 
    assertEquals("From: Tietue line: 59", "Tekniikka", miel.anna(2)); 
    assertEquals("From: Tietue line: 60", "3", miel.anna(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString73 */
  @Test
  public void testString73() {    // Tietue: 73
    Mielenkiinto miel = new Mielenkiinto(); 
    assertEquals("From: Tietue line: 75", "Vahvuuden täytyy olla välillä 1-5", miel.aseta(3,"kissa")); 
    assertEquals("From: Tietue line: 76", null, miel.aseta(3,"3")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTietue87 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testTietue87() throws CloneNotSupportedException {    // Tietue: 87
    Mielenkiinto miel = new Mielenkiinto(); 
    miel.parse("   2  |  2  |   Tekniikka  | 5 "); 
    Object kopio = miel.clone(); 
    assertEquals("From: Tietue line: 92", miel.toString(), kopio.toString()); 
    miel.parse("   1   |  1  |   Perhe  | 3"); 
    assertEquals("From: Tietue line: 94", false, kopio.toString().equals(miel.toString())); 
    assertEquals("From: Tietue line: 95", true, kopio instanceof Mielenkiinto); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString105 */
  @Test
  public void testString105() {    // Tietue: 105
    Mielenkiinto mielenkiinto = new Mielenkiinto(); 
    mielenkiinto.parse("   2   |  2  |   Tekniikka  | 5 "); 
    { String _l_=mielenkiinto.toString(),_r_="2\\|2\\|Tekniikka\\|5.*"; if ( !_l_.matches(_r_) ) fail("From: Tietue line: 108" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}